services:
  duckdb:
    build: .
    container_name: duckdb
    ports:
      - "4213:80"
      - "4214:4213"
    volumes:
      - ./data:/db
      - ./data/notebooks:/root/.duckdb/extension_data/ui
    tty: true
